kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: drone-test-vue  

## 执行系统平台，不然在build会一直pending
## 预设是 linux / amd64
platform:
  os: linux
  arch: arm64

## 克隆代码时，depth=1 更快速
clone:
  depth: 1

steps:
  - name: build # 流水线名称
    image: node:20.6.1
    commands:
      - npm config set registry https://registry.npmmirror.com
      - npm install
      - npm run build

  - name: build-docker
    image: plugins/docker
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: docker
        path: /var/run/docker.sock # 挂载宿主机的docker
    settings:
      context: /drone/src
    commands: # 定义在Docker容器中执行的shell命令
      - echo stop container
      - docker stop `docker ps -a | grep drone-test-vue | awk '{print $1}'` 
      - echo remove image
      - docker rm -f `docker ps -a | grep drone-test-vue | awk '{print $1}'` 
      - echo build new images
      - docker build -t drone-test-vue .
      - echo run container
      - docker run -p 8080:80 --name drone-test-vue -d drone-test-vue

volumes: # 定义流水线挂载目录，用于共享数据的
  - name: docker
    host:
      path: /var/run/docker.sock
